"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var VariableDiscount_1 = require("./VariableDiscount");
var FixedDiscount_1 = require("./FixedDiscount");
var NoDiscount_1 = require("./NoDiscount");
var Product_1 = require("./Product");
var ShoppingBasket_1 = require("./ShoppingBasket");
var cart = new ShoppingBasket_1.ShoppingBasket();
cart.addProduct(new Product_1.Product('Chair', 25, new FixedDiscount_1.FixedDiscount(10)));
cart.addProduct(new Product_1.Product('Table', 50, new VariableDiscount_1.VariableDiscount(25)));
cart.addProduct(new Product_1.Product('Bed', 100, new NoDiscount_1.NoDiscount()));
cart.addProduct(new Product_1.Product('Sofa', 299, new VariableDiscount_1.VariableDiscount(33)));
var tableElement = document.querySelector('#cart tbody');
tableElement.innerHTML = '';
cart.products.forEach(function (product) {
    var tr = document.createElement('tr');
    var td = document.createElement('td');
    td.innerText = product.name;
    tr.appendChild(td);
    td = document.createElement('td');
    td.innerText = product.originalPrice.toFixed(2) + ' €';
    tr.appendChild(td);
    td = document.createElement('td');
    td.innerText = product.calculatePrice().toFixed(2) + ' €';
    tr.appendChild(td);
    td = document.createElement('td');
    td.innerText = product.showCalculation();
    tr.appendChild(td);
    tableElement.appendChild(tr);
});
